### ISSUE TITLE
Asking about data

### ISSUE THREAD

**Issue by acse-yl7419** [jpcorb20/covid19-transmission-ukf#3]
Hello, JP. Sorry to disturb you. I am Fiona, a student who is struggling for learning data assimilation methods related to covid19. I see your project which is very helpful to me. However I noticed you didn't upload “data.xlsx”. So would you mind uploading raw data file? Thank you very very much.

**Comment by jpcorb20** [comment]
Hello, I will look into my local repo to upload them soon. Thank you for your interest !

**Comment by jpcorb20** [comment]
It is now available

**Comment by acse-yl7419** [comment]
Thank you very much! Thanks for your reply!
